version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/farm_fresh_shop
      - SECRET_KEY=your-secret-key-for-jwt-please-change-in-production
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=farm_fresh_shop
    ports:
      - "5432:5432"

volumes:
  postgres_data:
