"""changes shipping zip to null

Revision ID: 2e4980de9450
Revises: 9d17ef46fafc
Create Date: 2025-05-23 21:05:57.131390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4980de9450'
down_revision: Union[str, None] = '9d17ef46fafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'shipping_zip',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'shipping_zip',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
