"""added fields to order schema

Revision ID: 6f7f4a0722d0
Revises: ae346a508843
Create Date: 2025-06-19 15:40:41.821560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7f4a0722d0'
down_revision: Union[str, None] = 'ae346a508843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('country', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('whatsapp_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('email_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('order_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_notes')
    op.drop_column('orders', 'email_address')
    op.drop_column('orders', 'whatsapp_number')
    op.drop_column('orders', 'country')
    op.drop_column('orders', 'shipping_city')
    # ### end Alembic commands ###
