"""Add delivery options for mangoes

Revision ID: 938e2b5bb833
Revises: 77148e96f820
Create Date: 2025-05-19 03:04:41.527852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938e2b5bb833'
down_revision: Union[str, None] = '77148e96f820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_type', sa.Enum('PICKUP', 'DOORSTEP', name='deliverytype'), nullable=False))
    op.add_column('orders', sa.Column('is_mango_delivery', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('airport_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('airport_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_id', sa.String(), nullable=False))
    op.alter_column('orders', 'shipping_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'shipping_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('orders', 'shipping_state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'shipping_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('orders', 'payment_id')
    op.drop_column('orders', 'airport_name')
    op.drop_column('orders', 'airport_code')
    op.drop_column('orders', 'is_mango_delivery')
    op.drop_column('orders', 'delivery_type')
    # ### end Alembic commands ###
