"""made payment_id nullable

Revision ID: ae346a508843
Revises: 2e4980de9450
Create Date: 2025-05-24 05:22:47.765553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae346a508843'
down_revision: Union[str, None] = '2e4980de9450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'payment_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'payment_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
